sugarcube-2:
  macros:
    img:
      name: img
    stats:
      name: stats
    smod:
      name: smod
    renderbody_statbased:
      name: renderbody_statbased
    c:
      name: c
    render:
      name: render
