# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the source branch
  push:
    branches: [ source, main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: get tweego
        uses: schmiddim/action-wget-unzip@v2
        with:
          url: https://github.com/tmedwards/tweego/releases/download/v2.1.1/tweego-2.1.1-linux-x64.zip
          destination: tweego
          
      - name: remove storyformats
        run: rm -r tweego/storyformats/*
        
      - name: get sugarcube
        uses: schmiddim/action-wget-unzip@v2
        with:
          url: https://github.com/tmedwards/sugarcube-2/releases/download/v2.36.1/sugarcube-2.36.1-for-twine-2.1-local.zip
          destination: tweego/storyformats
          
      - name: build
        run: sudo chmod +x tweego/tweego && ls -l tweego && ls -l tweego/storyformats && tweego/tweego -o index.html src 
        
      - name: prepare
        run: mkdir public && mv index.html img public
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
